### ISSUE TITLE
`ipfs.wrappers.io` Short Term Pinning

### ISSUE THREAD

**Issue by dOrgJelli** [polywrap/nodes#48]
The `ipfs.wrappers.io` service should support short term (24 hours) pinning for valid wrappers that are deployed to the persistence node, as defined in this SLA: https://github.com/polywrap/monorepo/issues/742

**Comment by evanjacobs** [comment]
What happens after 1 day? Is this simply the cache refresh rate (i.e. valid wrappers will continue to be "discovered" and added to the cache every day)?

**Comment by dOrgJelli** [comment]
If the wrapper has not been added to an ENS domain before the 24 hour limit is reached, the persistence node will no longer be required to keep the wrapper pinned, and the background IPFS node could discard the file during garbage collection.

**Comment by evanjacobs** [comment]
Thanks for the clarification.

Is there a future feature planned where we could help to create/update the relevant ENS domain as part of the deployment process? It would be great to get all of that done in one workflow.

**Comment by dOrgJelli** [comment]
Yes this is just the first phase in our idealized deployment flow. @nerfZael should have a document that he can send your way which describes the various phases.

**Comment by nerfZael** [comment]
> Thanks for the clarification.
> 
> Is there a future feature planned where we could help to create/update the relevant ENS domain as part of the deployment process? It would be great to get all of that done in one workflow.

I think this is just publishing to ENS with the CLI , this is already possible through the wrappers cli https://www.npmjs.com/package/@nerfzael/wrappers
But it does have a feature missing, which is to publish just an IPFS hash to ENS (instead of first publishing the build folder to IPFS and then IPFS hash to ENS)

**Comment by dOrgJelli** [comment]
This can be closed, as we've implemented support for pinning an wrapper on IPFS to wrappers.io freely.
